# Generated by Django 3.2.7 on 2021-10-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20211026_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='price_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
